In [1]:
!git clone https://github.com/yhenon/pytorch-retinanet.git
!apt-get install tk-dev python-tk
!pip install pandas
!pip install pycocotools
!pip install opencv-python
!pip install requests

Cloning into 'pytorch-retinanet'...
remote: Enumerating objects: 225, done.
remote: Total 225 (delta 0), reused 0 (delta 0), pack-reused 225
Receiving objects: 100% (225/225), 1.01 MiB | 35.79 MiB/s, done.
Resolving deltas: 100% (114/114), done.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
tk-dev is already the newest version (8.6.0+9).
python-tk is already the newest version (2.7.17-1~18.04).
0 upgraded, 0 newly installed, 0 to remove and 29 not upgraded.


In [2]:
#!wget https://drive.google.com/open?id=1yLmjq3JtXi841yXWBxst0coAgR26MNBS
!gdown --id 1yLmjq3JtXi841yXWBxst0coAgR26MNBS

Downloading...
From: https://drive.google.com/uc?id=1yLmjq3JtXi841yXWBxst0coAgR26MNBS
To: /content/coco_resnet_50_map_0_335_state_dict.pt
152MB [00:01, 104MB/s]


In [ ]:
import torch
import torchvision.models as models

retinanet = models.resnet50(num_classes=3,)
retinanet.load_state_dict(torch.load('/content/coco_resnet_50_map_0_335_state_dict.pt'),strict=False)

_IncompatibleKeys(missing_keys=['fc.weight', 'fc.bias'], unexpected_keys=['fpn.P5_1.weight', 'fpn.P5_1.bias', 'fpn.P5_2.weight', 'fpn.P5_2.bias', 'fpn.P4_1.weight', 'fpn.P4_1.bias', 'fpn.P4_2.weight', 'fpn.P4_2.bias', 'fpn.P3_1.weight', 'fpn.P3_1.bias', 'fpn.P3_2.weight', 'fpn.P3_2.bias', 'fpn.P6.weight', 'fpn.P6.bias', 'fpn.P7_2.weight', 'fpn.P7_2.bias', 'regressionModel.conv1.weight', 'regressionModel.conv1.bias', 'regressionModel.conv2.weight', 'regressionModel.conv2.bias', 'regressionModel.conv3.weight', 'regressionModel.conv3.bias', 'regressionModel.conv4.weight', 'regressionModel.conv4.bias', 'regressionModel.output.weight', 'regressionModel.output.bias', 'classificationModel.conv1.weight', 'classificationModel.conv1.bias', 'classificationModel.conv2.weight', 'classificationModel.conv2.bias', 'classificationModel.conv3.weight', 'classificationModel.conv3.bias', 'classificationModel.conv4.weight', 'classificationModel.conv4.bias', 'classificationModel.output.weight', 'classificati

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!cp '/content/drive/MyDrive/Objectdetection/images.tar' '/content/images.tar'

In [ ]:
!tar -xvf  '/content/images.tar' -C '/content/'

images/
images/test/
images/test/201.png
images/test/201.xml
images/test/202.png
images/test/202.xml
images/test/203.png
images/test/203.xml
images/test/204.png
images/test/204.xml
images/test/205.png
images/test/205.xml
images/test/206.png
images/test/206.xml
images/test/207.png
images/test/207.xml
images/test/208.png
images/test/208.xml
images/test/209.png
images/test/209.xml
images/test/210.png
images/test/210.xml
images/test/211.png
images/test/211.xml
images/test/212.png
images/test/212.xml
images/test/213.png
images/test/213.xml
images/test/214.png
images/test/214.xml
images/test/215.png
images/test/215.xml
images/test/216.png
images/test/216.xml
images/test/217.png
images/test/217.xml
images/test/218.png
images/test/218.xml
images/test/219.png
images/test/219.xml
images/test/220.png
images/test/220.xml
images/test/221.png
images/test/221.xml
images/test/222.png
images/test/222.xml
images/test/223.png
images/test/223.xml
images/test/224.png
images/test/224.xml
images/test/225.png

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
import requests
import urllib
import os
from PIL import Image

# from keras_retinanet import models
# from keras_retinanet.utils.image import preprocess_image, resize_image
# from keras_retinanet.utils.visualization import draw_box, draw_caption
# from keras_retinanet.utils.colors import label_color

In [ ]:
df_train = pd.read_csv('/content/train_labels.csv')
df_train.head()

filename  width  height       class  xmin  ymin  xmax  ymax
0    0.png    800     600  Red_signal   127   260   184   381
1    0.png    800     600  Red_signal   373   263   431   387
2    0.png    800     600  Red_signal   622   266   680   391
3    1.png    800     600  Red_signal   125   260   183   382
4    1.png    800     600  Red_signal   375   262   429   387

In [ ]:
df_test = pd.read_csv('/content/test_labels.csv')
df_test.head()

filename  width  height         class  xmin  ymin  xmax  ymax
0  201.png    800     600  Green_signal   205   337   247   434
1  201.png    800     600  Green_signal   400   344   446   443
2  201.png    800     600  Green_signal   595   348   640   445
3  202.png    800     600    Red_signal    47   129   116   294
4  202.png    800     600    Red_signal   376   135   450   300

In [ ]:
train_data = df_train.iloc[:,[0,4,5,6,7,3]]
train_data.head()

filename  xmin  ymin  xmax  ymax       class
0    0.png   127   260   184   381  Red_signal
1    0.png   373   263   431   387  Red_signal
2    0.png   622   266   680   391  Red_signal
3    1.png   125   260   183   382  Red_signal
4    1.png   375   262   429   387  Red_signal

In [ ]:
test_data = df_test.iloc[:,[0,4,5,6,7,3]]
test_data.head()

filename  xmin  ymin  xmax  ymax         class
0  201.png   205   337   247   434  Green_signal
1  201.png   400   344   446   443  Green_signal
2  201.png   595   348   640   445  Green_signal
3  202.png    47   129   116   294    Red_signal
4  202.png   376   135   450   300    Red_signal

In [ ]:
train_path = '/content/images/train'
train_data['filename'] = train_data['filename'].apply(lambda x:x.replace(x,os.path.join(train_path,x)))
train_data.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


filename  xmin  ymin  xmax  ymax       class
0  /content/images/train/0.png   127   260   184   381  Red_signal
1  /content/images/train/0.png   373   263   431   387  Red_signal
2  /content/images/train/0.png   622   266   680   391  Red_signal
3  /content/images/train/1.png   125   260   183   382  Red_signal
4  /content/images/train/1.png   375   262   429   387  Red_signal

In [ ]:
test_path = '/content/images/test'
test_data['filename'] = test_data['filename'].apply(lambda x:x.replace(x,os.path.join(test_path,x)))
test_data.head()

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


filename  xmin  ymin  xmax  ymax         class
0  /content/images/test/201.png   205   337   247   434  Green_signal
1  /content/images/test/201.png   400   344   446   443  Green_signal
2  /content/images/test/201.png   595   348   640   445  Green_signal
3  /content/images/test/202.png    47   129   116   294    Red_signal
4  /content/images/test/202.png   376   135   450   300    Red_signal

In [ ]:
train_data.to_csv('/content/train_annotations.csv', index=False, header=None)

In [ ]:
test_data.to_csv('/content/test_annotations.csv', index=False, header=None)

In [ ]:
classes = ['Red_signal','Green_signal','Yellow_signal']
with open('/content/classes.csv', 'w') as f:
  for i, class_name in enumerate(classes):
    f.write(f'{class_name},{i}\n')

In [ ]:
!head /content/train_annotations.csv

/content/images/train/0.png,127,260,184,381,Red_signal
/content/images/train/0.png,373,263,431,387,Red_signal
/content/images/train/0.png,622,266,680,391,Red_signal
/content/images/train/1.png,125,260,183,382,Red_signal
/content/images/train/1.png,375,262,429,387,Red_signal
/content/images/train/1.png,622,268,678,391,Red_signal
/content/images/train/10.png,10,144,80,304,Green_signal
/content/images/train/10.png,331,153,402,312,Green_signal
/content/images/train/10.png,643,157,716,321,Green_signal
/content/images/train/100.png,89,516,103,549,Green_signal


In [ ]:
!head /content/classes.csv

Red_signal,0
Green_signal,1
Yellow_signal,2


In [ ]:
!head /content/test_annotations.csv

/content/images/test/201.png,205,337,247,434,Green_signal
/content/images/test/201.png,400,344,446,443,Green_signal
/content/images/test/201.png,595,348,640,445,Green_signal
/content/images/test/202.png,47,129,116,294,Red_signal
/content/images/test/202.png,376,135,450,300,Red_signal
/content/images/test/202.png,711,139,785,306,Red_signal
/content/images/test/203.png,206,337,246,436,Green_signal
/content/images/test/203.png,401,342,447,443,Green_signal
/content/images/test/203.png,597,349,642,448,Green_signal
/content/images/test/204.png,202,334,246,436,Green_signal


In [47]:
!python '/content/pytorch-retinanet/train.py' --dataset csv --csv_train '/content/train_annotations.csv' --csv_classes '/content/classes.csv' --csv_val '/content/test_annotations.csv'

Streaming output truncated to the last 5000 lines.
Epoch: 31 | Iteration: 53 | Classification loss: 0.00008 | Regression loss: 0.08621 | Running loss: 0.08485
Epoch: 31 | Iteration: 54 | Classification loss: 0.00257 | Regression loss: 0.12042 | Running loss: 0.08481
Epoch: 31 | Iteration: 55 | Classification loss: 0.00078 | Regression loss: 0.09387 | Running loss: 0.08489
Epoch: 31 | Iteration: 56 | Classification loss: 0.00000 | Regression loss: 0.00000 | Running loss: 0.08489
Epoch: 31 | Iteration: 57 | Classification loss: 0.00694 | Regression loss: 0.10331 | Running loss: 0.08499
Epoch: 31 | Iteration: 58 | Classification loss: 0.00079 | Regression loss: 0.05285 | Running loss: 0.08498
Epoch: 31 | Iteration: 59 | Classification loss: 0.00347 | Regression loss: 0.09801 | Running loss: 0.08496
Epoch: 31 | Iteration: 60 | Classification loss: 0.00276 | Regression loss: 0.08506 | Running loss: 0.08514
Epoch: 31 | Iteration: 61 | Classification loss: 0.00000 | Regression loss: 0.00000 |

In [ ]:
#python coco_validation.py --coco_path ~/path/to/coco --model_path /path/to/model/coco_resnet_50_map_0_335_state_dict.pt

In [58]:
%matplotlib inline
!python '/content/pytorch-retinanet/visualize_single_image.py' --image_dir '/content/images/test/' --model_path '/content/csv_retinanet_50.pt' --class_list '/content/classes.csv'

torch.Size([1, 3, 640, 832]) (600, 800, 3) 1.0133333333333334
Elapsed time: 0.1907176971435547
tensor([154.1027, 495.1227, 172.1348, 535.5162], device='cuda:0') torch.Size([9])
tensor([239.2986, 498.6310, 259.7625, 538.0731], device='cuda:0') torch.Size([9])
tensor([325.0405, 499.2606, 344.8003, 539.9219], device='cuda:0') torch.Size([9])
tensor([239.8797, 497.8114, 259.3898, 538.6175], device='cuda:0') torch.Size([9])
tensor([154.1027, 495.1227, 172.1348, 535.5162], device='cuda:0') torch.Size([9])
<PIL.Image.Image image mode=RGB size=800x600 at 0x7F1E14E41C90>
torch.Size([1, 3, 640, 832]) (600, 800, 3) 1.0133333333333334
Elapsed time: 0.12847089767456055
tensor([346.7093, 496.2153, 366.2315, 538.3473], device='cuda:0') torch.Size([8])
tensor([171.0620, 492.7219, 189.7282, 534.0157], device='cuda:0') torch.Size([8])
tensor([259.1869, 493.3236, 278.7236, 534.5955], device='cuda:0') torch.Size([8])
tensor([171.0620, 492.7219, 189.7282, 534.0157], device='cuda:0') torch.Size([8])
tensor(